name: Build Catppuccino

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            shell: bash
          - os: ubuntu-latest  
            shell: bash
          - os: windows-latest
            shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: List files
        run: ${{ matrix.shell == 'powershell' && 'ls' || 'ls -la' }}

      - name: Make gradlew executable
        if: matrix.shell == 'bash'
        run: chmod +x ./gradlew

      - name: Build project
        run: ${{ matrix.shell == 'powershell' && '.\gradlew.bat build' || './gradlew build' }}

      - name: Copy resources
        run: |
          if [ "${{ matrix.shell }}" = "powershell" ]; then
            cp .\build\resources\main\* .\build\classes\kotlin\main\ -r -Force
          else
            cp -r ./build/resources/main/* ./build/classes/kotlin/main/
          fi

      - name: Copy dependencies
        run: ${{ matrix.shell == 'powershell' && '.\gradlew.bat copyDependencies' || './gradlew copyDependencies' }}

      - name: Change to build directory
        run: ${{ matrix.shell == 'powershell' && 'cd build' || 'cd build' }}

      - name: Package as native executable
        run: |
          if [ "${{ matrix.shell }}" = "powershell" ]; then
            jpackage -t app-image -n catppuccino -p "build\libs\lib;build\classes\kotlin\main" -m me.cdh/me.cdh.Main --jlink-options "--compress zip-9 --strip-native-commands --strip-debug --no-header-files --no-man-pages" --dest output --icon build\classes\kotlin\main\catppuccino.ico --copyright curtishd
          else
            jpackage -t app-image -n catppuccino -p "./build/libs/lib:./build/classes/kotlin/main" -m me.cdh/me.cdh.Main --jlink-options "--compress zip-9 --strip-native-commands --strip-debug --no-header-files --no-man-pages" --dest output --copyright curtishd
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: catppuccino-${{ matrix.os }}
          path: ${{ matrix.shell == 'powershell' && '.\\output' || './output' }}