on: [ push, workflow_dispatch ]
jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ls -la
      - run: chmod +x ./gradlew
      - run: ./gradlew build
      - run: cp -r ./build/resources/main/* ./build/classes/kotlin/main/
      - run: ./gradlew copyDependencies
      - run: cd build
        name: Packaged as native executable
      - run: jpackage -t app-image -n catppuccino -p "./build/libs/lib:./build/classes/kotlin/main" -m me.cdh/me.cdh.MainKt --jlink-options "--compress zip-9 --strip-native-commands --strip-debug --no-header-files --no-man-pages" --java-options "-Xmx50m" --dest output
      - uses: actions/upload-artifact@v4
        with:
          name: kitten
          path: ./output