on: [ push, workflow_dispatch ]
jobs:
  setup-java:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: powershell
      - run: .\gradlew.bat build
      - run: .\gradlew.bat copyResourcesToClass
      - run: .\gradlew.bat copyDependencies
      - run: cd build
      - run: jpackage -t app-image -n kitten -p "build\libs;build\classes\kotlin\main" -m me.cdh/me.cdh.MainKt --jlink-options "--compress zip-9 --strip-native-commands --strip-debug --no-header-files --no-man-pages" --dest output --icon build\classes\kotlin\main\Catppuccino.ico
      - uses: actions/upload-artifact@v4
        with:
          name: kitten
          path: .\output